### PR TITLE
Calendar progress item fixes and cleanup

### PR DESCRIPTION
**Pull request by the-j0k3r**
few updates, one fix and improvements

### CODE REVIEW

**Comment by vednoc** [comment]
Should I add this, too? It would be a bit more consistent than 🟧 used only in the calendar. 🙃 

image

**Comment by the-j0k3r** [comment]
> Should I add this, too? It would be a bit more consistent than orange_square used only in the calendar. upside_down_face

No idea, is that accent colors?

**Comment by vednoc** [comment]
No. I was talking about small radius, which on SVG elements can be achieved by using `clip-path` property.

**Comment by the-j0k3r** [comment]
> No. I was talking about small radius, which on SVG elements can be achieved by using `clip-path` property.

Im not sure if making those things smaller is better but a really small radius maybe.

**Review by vednoc — APPROVED** [review]

**Comment by the-j0k3r** [comment]
> No. I was talking about small radius, which on SVG elements can be achieved by using `clip-path` property.

What about changing the legend radius to match the calendar?

**Pull request merged**
